create table Movies_Metadata(
   adult boolean,
   belongs_to_collection text,
   budget int,
   genres text,
   homepage varchar(250),
   id int,
   imdb_id varchar(10),
   original_language varchar(10),
   original_title varchar(110),
   overview varchar(1000),
   popularity float,
   poster_path varchar(40),
   production_companies text,
   production_countries text,
   release_date date,
   revenue bigint,
   runtime float,
   spoken_languages text,
   status varchar(20),
   tagline varchar(300),
   title varchar(110),
   video boolean,
   vote_average float,
   vote_count int
);